default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost


development:
  <<: *default
  database: shoppingify_development #　DBの名前。「sample」の部分をアプリの名前に変更すると分かりやい

test:
  <<: *default
  database: shoppingify_test #　DBの名前。「sample」の部分をアプリの名前に変更すると分かりやい

production:
  <<: *default
  database: shoppingify_production
  username: shoppingify
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>